BACKEND/Django/blog/src/blog/blog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls", namespace="users")),
    path('', include("web.urls", namespace="web")),
    path('posts/', include("posts.urls", namespace="posts"))
]


if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + 
        static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    )

BACKEND/Django/blog/src/blog/posts/urls.py
from django.urls import path
from posts import views


app_name = "posts"


urlpatterns = [
    path('create/',views.create_post, name="create_post"),
    path('my-posts/',views.my_posts, name="my_posts"),
    path('delete/<int:id>/',views.delete_post, name="delete_post"),
    path('draft/<int:id>/',views.draft_post, name="draft_post"),
    path('edit/<int:id>/',views.edit_post, name="edit_post"),
]

BACKEND/Django/blog/src/blog/web/urls.py
from django.urls import path
from web import views


app_name = "web"


urlpatterns = [
    path('',views.index, name="index"),
    path('<int:id>/',views.post, name="post"),
]

BACKEND/Django/blog/src/blog/posts/models.py
from django.db import models
from ckeditor.fields import RichTextField


class Author(models.Model):
    name = models.CharField(max_length=255)
    user = models.OneToOneField("auth.User", on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Category(models.Model):
    title = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.id


class Post(models.Model):
    title = models.CharField(max_length=255)
    short_description = models.TextField()
    description = RichTextField()
    categories = models.ManyToManyField("posts.Category")
    time_to_read = models.CharField(max_length=128)
    featured_image = models.ImageField(upload_to="posts/")

    author = models.ForeignKey("posts.Author", on_delete=models.CASCADE)
    published_date = models.DateField()
    is_draft = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.title

BACKEND/Django/blog/src/blog/posts/forms.py
from django import forms
from posts.models import Post


class PostForm(forms.ModelForm):
    tags = forms.CharField(widget=forms.TextInput(attrs={"class":"input"}), label="Tags (Comma Seperated)")

    class Meta:
        model = Post
        exclude = ('author', 'published_date', 'is_deleted', 'categories')
        
        widgets = {
            "time_to_read" : forms.TextInput(attrs={"class":"input"}),
            "title" : forms.TextInput(attrs={"class":"input"}),
            "short_description" : forms.Textarea(attrs={"class":"input"}),
        }

        error_message = {
            "time_to_read":{
                "required":"Time to read field is required "
            },
            "description":{
                "required":"Description field is required"
            },
            "short_description":{
                "required":"Short description field is required"
            },
            "title":{
                "required":"Title field is required"
            },
            "featured_image":{
                "required":"Featured image field is required"
            },
        }

BACKEND/Django/blog/src/blog/posts/views.py
import datetime
import json

from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from main.functions import generate_form_errors, paginate_instances
from posts.forms import PostForm
from posts.models import Author, Category, Post
from main.decorators import allow_self


@login_required(login_url="/users/login/")
def create_post(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():

            tags = form.cleaned_data['tags']
            print(tags)

            if not Author.objects.filter(user=request.user).exists():
                author = Author.objects.create(
                    user=request.user, name=request.user.username)
            else:
                author = request.user.author

            instance = form.save(commit=False)
            instance.published_date = datetime.date.today()
            instance.author = author
            instance.save()

            listed_tags = tags.split(",")
            for tag in listed_tags:
                category, created = Category.objects.get_or_create(
                    title=tag.strip())
                instance.categories.add(category)

                response_data = {
                    "title": "Successfully submitted",
                    "message": "Successfully submitted",
                    "status": "success",
                    "redirect": "yes",
                    "redirect_url": "/",
                }
        else:
            error_message = generate_form_errors(form)
            response_data = {
                "title": "form validation error",
                "message": str(error_message),
                "status": "error",
                "stable": "yes",
            }
        return HttpResponse(json.dumps(response_data), content_type="application/json")
    else:
        form = PostForm()
        context = {
            "title": "Create new Post",
            "form": form
        }

        return render(request, "posts/create.html", context)



@login_required(login_url="/users/login/")
def my_posts(request):
    posts = Post.objects.filter(author__user=request.user, is_deleted=False)
    instances = paginate_instances(request, posts)

    context={
        "title":"My Posts",
        "instances": instances,
    }
    return render(request, "posts/my-posts.html", context )



@login_required(login_url="/users/login/")
@allow_self
def delete_post(request, id):
    instance = get_object_or_404(Post.objects.filter(id=id))
    instance.is_deleted = True 
    instance.save()

    response_data = {
        "title": "Successfully deleted",
        "message": "Post deleted",
        "status": "success"
    }
    return HttpResponse(json.dumps(response_data), content_type="application/json")


@login_required(login_url="/users/login/")
@allow_self
def draft_post(request, id):
    instance = get_object_or_404(Post.objects.filter(id=id))
    instance.is_draft = not instance.is_draft
    instance.save()

    response_data = {
        "title": "Successfully changed",
        "message":"Post updated",
        "status":"success"
    }
    return HttpResponse(json.dumps(response_data), content_type="application/json")





@login_required(login_url="/users/login/")
@allow_self
def edit_post(request, id):
    instance = get_object_or_404(Post, id=id)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():

            tags = form.cleaned_data['tags']


            instance = form.save(commit=False)
            instance.save()

            instance.categories.clear( )

            listed_tags = tags.split(",")
            for tag in listed_tags:
                category, created = Category.objects.get_or_create(
                    title=tag.strip())
                instance.categories.add(category)

                response_data = {
                    "title": "Successfully submitted",
                    "message": "Successfully submitted",
                    "status": "success",
                    "redirect": "yes",
                    "redirect_url": "/",
                }
        else:
            error_message = generate_form_errors(form)
            response_data = {
                "title": "form validation error",
                "message": str(error_message),
                "status": "error",
                "stable": "yes",
            }
        return HttpResponse(json.dumps(response_data), content_type="application/json")
    else:
        category_string = ""
        for category in instance.categories.all():
            category_string += f"{category.title},"
        
        tags = {
            "tags":category_string[:-1]
        }
        form = PostForm(instance=instance, initial=tags )
        context = {
            "title": "Create new Post",
            "form": form
        }

        return render(request, "posts/create.html", context)

BACKEND/Django/blog/src/blog/templates/posts/create.html
{% extends 'base.html' %}
{% block content%}
{% load static %}
        <section id="edit-post-home">
            <section class="wrapper">   
                {% include "web/includes/header.html" %}
                <section class="spotlight">
                    <h3>Create new post</h3>
                    <form action="" class="ajax redirect" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                            <div class="form-field">
                                <label for="{{form.title.id_for_label}}" class="subheads" >
                                    {{form.title.label}}
                                </label>
                                {{form.title}}
                            </div>
                            <div class="form-field">
                                <label class="subheads" for="{{form.description.id_for_label}}">
                                    {{form.description.label}}
                                </label>
                                <div class="description">
                                    <div class="editor" data-field-id="{{form.description.id_for_label}}" style="display: inline-block;">
                                        {{form.description}}
                                    </div>
                                </div>
                            </div>
                            <div class="form-field">
                                <label class="subheads" for="{{form.short_description.id_for_label}}">
                                    {{form.short_description.label}}
                                </label>
                                {{ form.short_description}}
                            </div>
                            <div class="form-field">
                                <label class="subheads" for="{{ form.tags.id_for_label}}">
                                    {{ form.tags.label}}
                                </label>
                                <div class="description">
                                    {{ form.tags}}
                                </div>
                            </div>
                            <div class="form-field">
                                <label for="{{form.time_to_read.id_for_label}}" class="subheads" >
                                    {{form.time_to_read.label}}
                                </label>
                                {{form.time_to_read}}
                            </div>
                            <div class="form-field">
                                <label for="{{form.featured_image.id_for_label}}" class="subheads" >
                                    {{form.featured_image.label}}
                                </label>
                                {{form.featured_image}}
                            </div>
                            <div class="form-field"></div>
                                <label class="checkbox" >
                                    {{form.is_draft}}
                                    {{form.is_draft.label}}
                                </label>
                            </div>
                            <div class="form-field">
                                <input type="submit" value="Submit" />
                            </div>
                    </form>
                    {{form.media}}
                </section>
            </section>
        </section>
        <!-- <script src="/static/ckeditor/ckeditor-init.js" data-ckeditor-basepath="/static/ckeditor/ckeditor/" id="ckeditor-init-script"></script> -->
        <!-- <script src="{% static './js/ckeditor.js"></script> -->
        <script>ClassicEditor
            .create( document.querySelector( '.editor' ), {
                
                licenseKey: '',
                
                
                
            } )
            .then( editor => {
                window.editor = editor;
        
                
                
                
            } )
            .catch( error => {
                console.error( 'Oops, something went wrong!' );
                console.error( 'Please, report the following error on https://github.com/ckeditor/ckeditor5/issues with the build id and the error stack trace:' );
                console.warn( 'Build id: fbn1rnj89y5k-nohdljl880ze' );
                console.error( error );
            } );
        </script>

{% endblock %}

BACKEND/Django/blog/src/blog/templates/posts/my-posts.html
{% extends 'base.html' %} {% load static %} {% block content %} {% load paginator_tags %}
<section id="my-posts-home">
    <section class="wrapper">
        {% include 'web/includes/header.html' %}
        <section class="spotlight">
            <h3>{{title}}</h3>
            <ul class="posts">
                {% for my_post in instances %}
                <li class="post">
                    <div class="top">
                        <h5 class="title">{{my_post.title}}</h5>
                        <div class="buttons">
                            <a 
                                href="{% url 'posts:delete_post' id=my_post.id %}" 
                                class="danger action-button reload" 
                                data-text="Are you sure want to remove this post. You can't undo this action." 
                                data-title="Confirm Delete!" title="Delete!"

                            >
                                <img src="{% static './images/icons/delete.svg' %}" alt="Delete" />
                            </a>
                            <a href="{% url 'posts:edit_post' id=my_post.id %}" class="warning">
                                <img src="{% static './images/icons/pencil.svg' %}" alt="Edit" />
                            </a>
                            <a 
                                href="{% url 'posts:draft_post' id=my_post.id %}" 
                                class="
                                {% if my_post.is_draft %}
                                    success 
                                {% else %}
                                    danger
                                {% endif %}
                                    action-button reload" 
                                data-text="Are you sure want to update this post" 
                                data-title="Confirm Status!" 
                                title="Draft"
                            >
                                <img src="{% static './images/icons/sheet.svg' %}" alt="Edit" />
                            </a>
                        </div>
                    </div>
                    <p class="description">{{my_post.description|safe | truncatewords:20}}</p>
                    <div class="bottom">
                        <a href="{% url 'web:post' id=my_post.id %}" class="view">
                            View
                            <span>
                                <img src="{% static './images/icons/up-arrow.svg' %}" alt="Arrow" />
                            </span>
                        </a>
                        <p class="date">{{my_post.published_date}}</p>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </section>
        {% load_pagination instances %}
    </section>
</section>
{% endblock %}

BACKEND/Django/blog/src/blog/templates/posts/post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section id="single-page-home">
        <section class="wrapper">         
            {% include 'web/includes/header.html' %}
            <section class="single-page-spotlight">
                <div class="blog-category">
                    {% for category in instance.categories.all %}
                    <span class="category">
                        {{category.title}}
                    </span>
                    {% endfor %}
                    
                    <span class="read">
                        <span class="clock">
                            <img src="{% static './images/icons/clock.svg' %}" alt="Clock" />
                        </span>
                        {{instance.time_to_read}}
                    </span>
                </div>
                <h3 class="title">
                    {{instance.title}}
                </h3>
                <p class="description">
                    {{instance.short_description}}
                </p>
                <div class="post-thumbnail">
                    <img src="{{instance.featured_image.url}}" alt="Post-thumbnail">
                </div>
                <div class="details">
                    <span class="published">
                        <p class="written">
                            Written by
                        </p>
                        <p class="name">
                            {{instance.author}}
                        </p>
                    </span>
                    <span class="published">
                        <p class="written">
                            Published on
                        </p>
                        <p class="name">
                        {{instance.published_date}}
                        </p>
                    </span>
                    <ul class="social">
                        <li>
                            <a class="copy-link">
                                <span class="link">
                                    <img src="{% static './images/icons/copy-link.svg' %}" alt="Copy-link" />
                                </span>
                                Copy link
                            </a>
                        </li>
                        <li class="social-media">
                            <a target="_blank" href="https://twitter.com/intent/tweet?text={{request.build_absolute_uri}}">
                                <img src="{% static './images/icons/twitter.svg' %}" alt="Twitter" />
                            </a>
                        </li>

                        <li class="social-media">
                            <a target="_blank" href="https://www.facebook.com/harer.php?u={{request.build_absolute_uri}}">
                                <img src="{% static './images/icons/facebook.svg' %}" alt="Facebook" />
                            </a>
                        </li>
                        <li class="social-media">
                            <a target="_blank" href="https://api.whatsapp.com/send/?text={{request.build_absolute_uri}}">
                                <img src="{% static './images/icons/whatsapp.svg' %}" alt="Whatsapp" />
                            </a>
                        </li>
                    </ul>
                </div>
                <p class="detailed-description">{{instance.description |safe}}</p>
                </section>
        </section>
    </section>
{% endblock %}