BACKEND/Django/helloworld/src/helloworld/helloworld/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('web.urls', namespace="web")),
]

BACKEND/Django/helloworld/src/helloworld/web/urls.py
from unicodedata import name
from django.urls import path
from web.views import about, index

app_name = "web"

urlpatterns = [
    path("", index, name="index"),
    path("about-us/", about, name="about")
]

BACKEND/Django/helloworld/src/helloworld/web/models.py
from django.db import models

# Create your models here.

BACKEND/Django/helloworld/src/helloworld/web/views.py
from django.shortcuts import render



# Create your views here.
def index(request):
    my_name = "Junaid Hisham"
    context = {
        "name": my_name
    }
    return render(request, "index.html", context=context)


def about(request):
    return render(request, "about.html")

BACKEND/Django/helloworld/src/helloworld/templates/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{{title}}</title>
    </head>
    <body>
        <h1>About Page</h1>
        <a href="{% url 'web:index' %}">Home</a>
    </body>
</html>

BACKEND/Django/helloworld/src/helloworld/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="{% static './css/style.css' %}" />
        <script src="{% static './js/script.js' %}"></script>
        <title>{{title}}</title>
    </head>
    <body>
        <h1>Hello {{name}}</h1>
        <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad
            perferendis iste voluptatibus mollitia provident molestias
            necessitatibus adipisci reiciendis ab illo.
        </p>
        <img src="{% static 'images/MyPhoto.jpg' %}" alt="Image" />
        <a href="{% url 'web:about' %}">About</a>
    </body>
</html>